# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a20ad4e18ad7588c42de1dd79253158791d57db27f3a5f08ffb1ff4294d5cde9ee681aec12ee7aa8bcda335e4231820d114d96e1fcc1ece19e9ea160607efd

test:
  secret_key_base: 54391bc03838d501226df41d9868c18f0f58e82cb1e130389df845b7aa97b6023ab9d43776a744ca9d887b43fb9731cb20cf2681fbb200d9707994a8591a1ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
